logging:
  level:
    root: info
spring:
  mvc:
    static-path-pattern: /webapp/**
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/waiting
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\KIT\\2022-1\\Capstone\\image
