spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/waiting
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\KIT\\2022-1\\Capstone\\image
  profiles:
    include: real-db
  session:
    store-type: jdbc