logging:
  level:
    root: info
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /webapp/**
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
